# Site settings
title: Jitendra Kumar
subtitle: Machine Learning Blog
email: optimusprime8565@gmail.com
description: "machine learning blog."
baseurl: ""
url: "https://prime8565.github.io/"
github_username:  prime8565

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]

# Search settings
tipue_search:
  include:
    pages: true
  exclude:
    files: [index.md, search.html]